const TYPES = {
    CHANGE_STEP: "CHANGE_STEP",
    REQUEST_TEMPLATES: "REQUEST_TEMPLATES",
    REQUEST_TEMPLATES_SUCCESS: "REQUEST_TEMPLATES_SUCCESS",
    REQUEST_TEMPLATES_ERROR: "REQUEST_TEMPLATES_ERROR",
    UPDATE_HOST_INFORMATION: "UPDATE_HOST_INFORMATION"
}

export default TYPES;