const labels = {
    access_details: "Access details",
    add_discount: "Add Discount Code",
    address: "Address",
    apply_code: "Apply Code",
    availability: "Availability",
    capacity: "Capacity:",
    card_information: "Card information",
    card_number: "Card number",
    cardhold_name: "Cardholder Name",
    check_availability: "Check Availability",
    choose_the_package: "Choose the package for you",
    city: "City",
    cost: "Cost",
    country: "Country",
    description: "Description",
    disclaimers: "Disclaimers",
    discount_code: "Discount Code",
    insurance_information: "Insurance Information",
    email: "Email",
    enviroment_conditions: "Enviroment conditions",
    exp_date: "Exp. Date",
    first_name: "First Name",
    go_to_payment: "Go to Payment",
    home_phone: "Home Phone",
    host_information: "Host information",
    language: "Language",
    last_name: "Last Name",
    mobile_phone: "Mobile Phone",
    number_of_guest: "Number of Guests",
    package_information: "Package information",
    packages_will_be_available: "The packages will be available once you fill out all the fields",
    pay: "Pay",
    payment: "Payment",
    personal_information: "Personal information",
    phone: "Phone",
    price: "Price:",
    registration: "Registration",
    search: "Search",
    security_details: "Security details",
    select_category: "Select a category according to your activity",
    select_date: "Select the date you want for your activity",
    select_time_frame: "Select the time frame for your activity",
    state: "State",
    subtotal: "Subtotal",
    summary: "Summary",
    thanks: "Thanks for helping to cover the processing frees",
    time_frame: "Time Frame:",
    to: "to",
    total: "Total",
    zip: "Zip/Code",
    error_select_category: "Please select a category",
    error_select_date: "Please select a valid date",
    error_time_range: "Please select a correct range",
    error_capacity: "Please the guest must be greater than or equal to zero",
}

export default labels