export const labelsEnglish = {
    access_details: "Access details",
    add_discount: "Add Discount Code",
    address: "Address",
    apply_code: "Apply Code",
    availability: "Availability",
    capacity: "Capacity:",
    card_information: "Card information",
    card_number: "Card number",
    cardhold_name: "Cardholder Name",
    check_availability: "Check Availability",
    choose_the_package: "Choose the package for you",
    city: "City",
    cost: "Cost",
    country: "Country",
    description: "Description",
    disclaimers: "Disclaimers",
    discount_code: "Discount Code",
    insurance_information: "Insurance Information",
    email: "Email",
    enviroment_conditions: "Enviroment conditions",
    exp_date: "Exp. Date",
    first_name: "First Name",
    go_to_payment: "Go to Payment",
    home_phone: "Home Phone",
    host_information: "Host information",
    language: "Language",
    last_name: "Last Name",
    mobile_phone: "Mobile Phone",
    number_of_guest: "Number of Guests",
    package_information: "Package information",
    packages_will_be_available: "The packages will be available once you fill out all the fields",
    pay: "Pay",
    payment: "Payment",
    personal_information: "Personal information",
    phone: "Phone",
    price: "Price:",
    reserve: "Reserve",
    registration: "Registration",
    search: "Search",
    security_details: "Security details",
    select_category: "Select a category according to your activity",
    select_category_input: "Select category",
    select_date: "Select the date you want for your activity",
    select_time_frame: "Select the time frame for your activity",
    state: "State",
    subtotal: "Subtotal",
    summary: "Summary",
    thanks: "Thanks for helping to cover the processing frees",
    time_frame: "Time Frame:",
    to: "to",
    total: "Total",
    zip: "Zip/Code",
    successful_operation: "You just succesfully reserved event ",
    continue_shopping: "Continue shopping",
    error_select_category: "Please select a category",
    error_select_date: "Please select a valid date",
    error_time_range: "Please select a correct range",
    error_capacity: "Please the guest must be greater than or equal to zero",
    error_first_name: "Please fill the first name",
    error_last_name: "Please fill the last name",
    error_email: "Please the email is required",
}

export const labelsSpanish = {
    access_details: "Detalles de acceso",
    add_discount: "Añadir código de descuento",
    address: "Direccion",
    apply_code: "Aplicar Código",
    availability: "Disponibilidad",
    capacity: "Capacidad:",
    card_information: "Información de la tarjeta",
    card_number: "Número de tarjeta",
    cardhold_name: "Nombre del titular",
    check_availability: "Comprobar disponibilidad",
    choose_the_package: "Elija el paquete para usted",
    city: "Ciudad",
    cost: "Costo",
    country: "País",
    description: "Descripción",
    disclaimers: "Descargo de responsabilidad",
    discount_code: "Código de descuento",
    insurance_information: "Información sobre el seguro",
    email: "Correo electrónico",
    enviroment_conditions: "Condiciones del entorno",
    exp_date: "Fecha de expiración",
    first_name: "Nombre",
    go_to_payment: "Ir a Pago",
    home_phone: "Teléfono de la casa",
    host_information: "Información del anfitrión",
    language: "Idioma",
    last_name: "Apellido",
    mobile_phone: "Teléfono móvil",
    number_of_guest: "Número de invitados",
    package_information: "Información del paquete",
    packages_will_be_available: "Los paquetes estarán disponibles una vez que haya rellenado todos los campos",
    pay: "Pagar",
    payment: "Pago",
    personal_information: "Información personal",
    phone: "Teléfono",
    price: "Precio:",
    reserve: "Reservar",
    registration: "Registro",
    search: "Buscar",
    security_details: "Detalles de seguridad",
    select_category: "Selecciona una categoría según tu actividad",
    select_category_input: "Selecciona la categoría",
    select_date: "Seleccione la fecha que desea para su actividad",
    select_time_frame: "Seleccione el periodo de tiempo para su actividad",
    state: "Estado",
    subtotal: "Subtotal",
    summary: "Resumen",
    thanks: "Gracias por ayudar a cubrir los gastos de tramitación",
    time_frame: "Tiempo:",
    to: "a",
    total: "Total",
    zip: "Código postal",
    successful_operation: "Acabas de reservar exitosamente el evento ",
    continue_shopping: "Continuar comprando",
    error_select_category: "Seleccione una categoría",
    error_select_date: "Seleccione una fecha válida",
    error_time_range: "Por favor, la hora de inicio no debe ser mayor que la hora final",
    error_capacity: "Por favor, el número de invitados debe ser mayor o igual a cero"
}

export default labelsEnglish